= finally

* try-execpt 예외 처리 문에서 예외의 발생 여부와 상관없이 무조건 실행됨
* 예외 발생시에도 반드시 실행되어야 하는 구문들을 처리할 때 사용

[source, python]
----
import sys

try:
    i = int(sys.argv[1])
    j = int(sys.argv[2])
    k = i / j
except IndexError:
    print("Usage: python Program.py <arg1> <arg2")
except ZeroDivisionError:
    print("can't divide by zero")
else:
    print(k)
finally:
    print("Thank you")
    raise ValueError
----

---

제어 흐름의 과정과 상관없이 실행해야 하는 코드를 위해 finally 절을 사용할 수 있습니다. 제어 흐름이 try 블록의 끝이 도달하여 정상적인 실행의 결과로 try 블록을 벗어나면 finally 블록의 코드가 실행됩니다. 또한 throw, break, continue 문 등으로 제어가 try 문을 벗어나면 finally 블록의 코드가 실행됩니다.

finally 절은 코드의 중복을 방지하고 예외가 발생한 후 리소스를 해제해야 하는 두 가지 상황에서 사용됩니다.

== 중복 코드 방지

try 블록과 execpt 블록 모두에서 반드시 사용되어야 하는 코드가 있는 경우 finally 블록으로 이동시켜 중복을 방지할 수 있습니다. 아래와 같은 코드가 있다면,

[source, python]
----
try:
    ...
    statements
except:
    statements
----

이를 아래와 같이 단순화 할 수 있습니다.

[source, python]
----
try:
    ...
except:
    ...
finally:
    ...
----


== 리소스 해제